struct stat;
struct rtcdate;
struct sigset_t;
struct timeval;
struct itimerval;

// system calls
int fork(void);
int exit(void) __attribute__((noreturn));
int wait(void);
int pipe(int*);
int write(int, const void*, int);
int read(int, void*, int);
int close(int);
int kill(int);
int exec(char*, char**);
int open(const char*, int);
int mknod(const char*, short, short);
int unlink(const char*);
int fstat(int fd, struct stat*);
int link(const char*, const char*);
int mkdir(const char*);
int chdir(const char*);
int dup(int);
int getpid(void);
char* sbrk(int);
int sleep(int);
int uptime(void);
int kill1(int,int);
int signal(int,void(*)(int));
int pause(void);
int sigprocmask(int, struct sigset_t*, struct sigset_t*);
int setitimer(int, struct itimerval*, struct itimerval*);
int getitimer(int, struct itimerval*);
int procSigState(int, int , int);

// ulib.c
int stat(const char*, struct stat*);
char* strcpy(char*, const char*);
void *memmove(void*, const void*, int);
char* strchr(const char*, char c);
int strcmp(const char*, const char*);
void printf(int, const char*, ...);
char* gets(char*, int max);
uint strlen(const char*);
void* memset(void*, int, uint);
void* malloc(uint);
void free(void*);
int atoi(const char*);
void sigaddset(struct sigset_t*, int);
void sigemptyset(struct sigset_t*);
